<a href="https://colab.research.google.com/github/aryancodes12/Advance-Machine-Learning/blob/main/bacic_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("/content/drive/MyDrive/CDPL SEM 3/dataset/SalaryData.csv")

In [9]:
df = pd.DataFrame(data)

In [8]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

BASIC EDA

In [15]:
#Checking columns of dataset
df.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  387 non-null    float64
 1   Gender               387 non-null    object
 2   Education Level      387 non-null    object
 3   Job Title            386 non-null    object
 4   Years of Experience  385 non-null    float64
 5   Salary               384 non-null    float64
dtypes: float64(3), object(3)
memory usage: 18.4+ KB

In [14]:
# checking shape of the data
df.shape

(390, 6)

In [17]:
#checking null values
df.isnull().sum()

Age                    3
Gender                 3
Education Level        3
Job Title              4
Years of Experience    5
Salary                 6
dtype: int64

In [18]:
 # value count of gender
 df['Gender'].value_counts()

Gender
Male       195
Female     180
FEMALE       3
MALE         2
female       2
Unknown      2
male         1
male         1
femle        1
Name: count, dtype: int64

In [19]:
 # value count of education level
 df['Education Level'].value_counts()

Education Level
Bachelor's    224
Master's       99
PhD            52
Bachelors       3
Masters         3
Phd             3
masters         2
bachelor        1
Name: count, dtype: int64

In [21]:
 # value count of Age
 df['Age'].value_counts()

Age
 33.0      24
 29.0      24
 35.0      22
 44.0      22
 31.0      21
 36.0      20
 30.0      18
 34.0      18
 45.0      18
 47.0      15
 38.0      15
 28.0      14
 43.0      13
 40.0      13
 32.0      12
 39.0      12
 41.0      12
 37.0      12
 42.0      11
 46.0      10
 48.0       9
 27.0       9
 49.0       8
 50.0       8
 26.0       7
 25.0       5
 51.0       5
 52.0       3
 22.0       2
 24.0       1
 23.0       1
 53.0       1
-5.0        1
 1000.0     1
Name: count, dtype: int64

In [23]:
# checking unique values in Gender
df['Gender'].unique()

array(['Male', 'Female', nan, 'male', 'FEMALE', 'male ', 'femle',
       'female', 'MALE', 'Unknown'], dtype=object)

In [24]:
# checking unique values in Education Level
df['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD', nan, 'Bachelors', 'Masters',
       'Phd', 'bachelor', 'masters'], dtype=object)

In [26]:
#Statistical description of the data
df.describe()

               Age  Years of Experience        Salary
count   387.000000           385.000000  3.840000e+02
mean     39.635659            10.050649  1.058993e+05
std      49.509188             6.896418  1.028712e+05
min      -5.000000             0.000000 -2.000000e+04
25%      31.000000             4.000000  5.500000e+04
50%      36.000000             9.000000  9.500000e+04
75%      44.000000            15.000000  1.400000e+05
max    1000.000000            50.000000  1.500000e+06